# Generated by Django 3.2.8 on 2021-10-18 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nasa', '0002_alter_post_photo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-date', 'title'], 'verbose_name': 'Пост', 'verbose_name_plural': 'Пости'},
        ),
        migrations.AlterField(
            model_name='post',
            name='photo',
            field=models.FileField(blank=True, upload_to='photos/%Y/%m/%d/', verbose_name='Фото'),
        ),
    ]
